// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1lNwn2TsLDsAr_N9h6pWekRinTBVkV_g',
    appId: '1:1034508809815:web:12bdcecfec9e3348aa5512',
    messagingSenderId: '1034508809815',
    projectId: 'apontamento-ti-delp',
    authDomain: 'apontamento-ti-delp.firebaseapp.com',
    storageBucket: 'apontamento-ti-delp.appspot.com',
    measurementId: 'G-0W2SPSK6RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUo2bF5BJPI4wZMyz-uiiK5jAxj-rK1d4',
    appId: '1:1034508809815:android:779dd752a0a21c88aa5512',
    messagingSenderId: '1034508809815',
    projectId: 'apontamento-ti-delp',
    storageBucket: 'apontamento-ti-delp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6UbBItO30ZUwCw4t-efAhnhG5lnaY1AU',
    appId: '1:1034508809815:ios:2c09f172bc866d7aaa5512',
    messagingSenderId: '1034508809815',
    projectId: 'apontamento-ti-delp',
    storageBucket: 'apontamento-ti-delp.appspot.com',
    iosClientId: '1034508809815-k72k3cfsn2rvelq1k82kue6jjkpchg3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.apontamentodelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6UbBItO30ZUwCw4t-efAhnhG5lnaY1AU',
    appId: '1:1034508809815:ios:2c09f172bc866d7aaa5512',
    messagingSenderId: '1034508809815',
    projectId: 'apontamento-ti-delp',
    storageBucket: 'apontamento-ti-delp.appspot.com',
    iosClientId: '1034508809815-k72k3cfsn2rvelq1k82kue6jjkpchg3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.apontamentodelp',
  );
}
